/**
 * Enterprise Adaptive Assessment Engine — Database Schema Migration
 * Module 4C-4: Adaptive Profiles, Personalized Tests, Learning Profiles,
 * Exam Readiness, Recommendations, Predictions, Analytics, Institute Configs
 */
const { Client } = require('pg');

const dbConfig = {
  host: 'db.dsduytkikxfgiyptdwex.supabase.co',
  port: 5432,
  user: 'postgres',
  password: '$anjana@123man',
  database: 'postgres'
};

async function migrate() {
  const db = new Client(dbConfig);
  await db.connect();
  console.log('[ADAPTIVE ENGINE SCHEMA] Connected. Creating tables...');

  // 1. adaptive_profiles — per-student continuously updated learning profile
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.adaptive_profiles (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL,
      exam_goal TEXT DEFAULT 'NEET 2027',
      target_rank INTEGER DEFAULT 5000,
      target_score INTEGER DEFAULT 550,
      subject_strengths_json JSONB DEFAULT '[]'::jsonb,
      subject_weaknesses_json JSONB DEFAULT '[]'::jsonb,
      chapter_strengths_json JSONB DEFAULT '[]'::jsonb,
      chapter_weaknesses_json JSONB DEFAULT '[]'::jsonb,
      topic_mastery_json JSONB DEFAULT '{}'::jsonb,
      concept_mastery_json JSONB DEFAULT '{}'::jsonb,
      retention_score NUMERIC(6,2) DEFAULT 100.0,
      memory_health_score NUMERIC(6,2) DEFAULT 100.0,
      learning_speed TEXT DEFAULT 'Medium',
      confidence_score NUMERIC(6,2) DEFAULT 50.0,
      study_consistency NUMERIC(6,2) DEFAULT 50.0,
      mistake_history_json JSONB DEFAULT '[]'::jsonb,
      revision_history_json JSONB DEFAULT '[]'::jsonb,
      current_difficulty_level TEXT DEFAULT 'Medium',
      total_tests_taken INTEGER DEFAULT 0,
      total_correct INTEGER DEFAULT 0,
      total_wrong INTEGER DEFAULT 0,
      total_skipped INTEGER DEFAULT 0,
      avg_response_time_sec NUMERIC(8,2) DEFAULT 0.0,
      last_active_at TIMESTAMPTZ DEFAULT now(),
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    )
  `);
  console.log('  ✓ adaptive_profiles');

  // 2. adaptive_tests — personalized tests generated by the adaptive engine
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.adaptive_tests (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL,
      test_id UUID,
      test_type TEXT NOT NULL DEFAULT 'Weak Area',
      generation_reason TEXT,
      difficulty_level TEXT DEFAULT 'Adaptive',
      parameters_json JSONB DEFAULT '{}'::jsonb,
      question_count INTEGER DEFAULT 0,
      score_achieved NUMERIC(8,2),
      accuracy_pct NUMERIC(6,2),
      time_taken_sec INTEGER,
      status TEXT DEFAULT 'Generated',
      created_at TIMESTAMPTZ DEFAULT now(),
      completed_at TIMESTAMPTZ
    )
  `);
  console.log('  ✓ adaptive_tests');

  // 3. adaptive_rules — configurable difficulty progression thresholds
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.adaptive_rules (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      rule_name TEXT NOT NULL,
      rule_type TEXT DEFAULT 'difficulty_progression',
      from_level TEXT NOT NULL,
      to_level TEXT NOT NULL,
      threshold_correct_pct NUMERIC(6,2) DEFAULT 70.0,
      threshold_time_sec NUMERIC(8,2),
      threshold_confidence NUMERIC(6,2),
      threshold_retention NUMERIC(6,2),
      is_active BOOLEAN DEFAULT true,
      priority INTEGER DEFAULT 0,
      metadata_json JSONB DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ DEFAULT now()
    )
  `);
  console.log('  ✓ adaptive_rules');

  // Seed default difficulty progression rules
  await db.query(`
    INSERT INTO public.adaptive_rules (rule_name, rule_type, from_level, to_level, threshold_correct_pct, priority)
    VALUES
      ('Easy to Medium', 'difficulty_progression', 'Easy', 'Medium', 70.0, 1),
      ('Medium to Hard', 'difficulty_progression', 'Medium', 'Hard', 75.0, 2),
      ('Hard to Very Hard', 'difficulty_progression', 'Hard', 'Very Hard', 80.0, 3),
      ('Very Hard to Adaptive', 'difficulty_progression', 'Very Hard', 'Adaptive', 85.0, 4),
      ('Downgrade Hard to Medium', 'difficulty_regression', 'Hard', 'Medium', 40.0, 5),
      ('Downgrade Medium to Easy', 'difficulty_regression', 'Medium', 'Easy', 35.0, 6)
    ON CONFLICT DO NOTHING
  `);
  console.log('  ✓ adaptive_rules seeded with default progression');

  // 4. recommendation_history — AI recommendation audit trail
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.recommendation_history (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL,
      recommendation_type TEXT NOT NULL,
      recommendation_text TEXT,
      priority INTEGER DEFAULT 0,
      reason TEXT,
      target_entity_json JSONB DEFAULT '{}'::jsonb,
      is_accepted BOOLEAN DEFAULT false,
      is_dismissed BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ DEFAULT now(),
      acted_at TIMESTAMPTZ
    )
  `);
  console.log('  ✓ recommendation_history');

  // 5. topic_mastery_profiles — granular per-chapter/topic mastery metrics
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.topic_mastery_profiles (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL,
      subject TEXT NOT NULL,
      chapter TEXT NOT NULL,
      topic TEXT,
      mastery_pct NUMERIC(6,2) DEFAULT 0.0,
      retention_pct NUMERIC(6,2) DEFAULT 100.0,
      accuracy_pct NUMERIC(6,2) DEFAULT 0.0,
      avg_speed_sec NUMERIC(8,2) DEFAULT 0.0,
      attempts INTEGER DEFAULT 0,
      correct INTEGER DEFAULT 0,
      wrong INTEGER DEFAULT 0,
      skipped INTEGER DEFAULT 0,
      last_attempted_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    )
  `);
  console.log('  ✓ topic_mastery_profiles');

  // 6. exam_readiness — composite readiness scores
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.exam_readiness (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL,
      exam_type TEXT DEFAULT 'NEET',
      syllabus_coverage_pct NUMERIC(6,2) DEFAULT 0.0,
      accuracy_pct NUMERIC(6,2) DEFAULT 0.0,
      speed_score NUMERIC(6,2) DEFAULT 0.0,
      retention_score NUMERIC(6,2) DEFAULT 0.0,
      memory_health_score NUMERIC(6,2) DEFAULT 0.0,
      difficulty_mastery_score NUMERIC(6,2) DEFAULT 0.0,
      consistency_score NUMERIC(6,2) DEFAULT 0.0,
      mock_performance_score NUMERIC(6,2) DEFAULT 0.0,
      overall_readiness_pct NUMERIC(6,2) DEFAULT 0.0,
      predicted_rank INTEGER,
      predicted_score NUMERIC(8,2),
      created_at TIMESTAMPTZ DEFAULT now()
    )
  `);
  console.log('  ✓ exam_readiness');

  // 7. personalized_plans — daily/weekly learning path plans
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.personalized_plans (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL,
      plan_date DATE DEFAULT CURRENT_DATE,
      plan_type TEXT DEFAULT 'daily',
      tasks_json JSONB DEFAULT '[]'::jsonb,
      total_tasks INTEGER DEFAULT 0,
      completed_tasks INTEGER DEFAULT 0,
      priority_subject TEXT,
      priority_chapter TEXT,
      is_completed BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ DEFAULT now()
    )
  `);
  console.log('  ✓ personalized_plans');

  // 8. adaptive_analytics — aggregated analytics snapshots
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.adaptive_analytics (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL,
      metric_name TEXT NOT NULL,
      metric_value NUMERIC(10,4) DEFAULT 0.0,
      dimension TEXT DEFAULT 'overall',
      period TEXT DEFAULT 'daily',
      snapshot_json JSONB DEFAULT '{}'::jsonb,
      recorded_at TIMESTAMPTZ DEFAULT now()
    )
  `);
  console.log('  ✓ adaptive_analytics');

  // 9. prediction_models — stored prediction model outputs
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.prediction_models (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL,
      model_type TEXT DEFAULT 'rank_prediction',
      exam_type TEXT DEFAULT 'NEET',
      predicted_score NUMERIC(8,2),
      predicted_rank INTEGER,
      confidence_interval NUMERIC(6,2) DEFAULT 80.0,
      input_features_json JSONB DEFAULT '{}'::jsonb,
      model_version TEXT DEFAULT 'v1.0',
      created_at TIMESTAMPTZ DEFAULT now()
    )
  `);
  console.log('  ✓ prediction_models');

  // 10. institute_adaptive_configs — institute-level adaptive test configurations
  await db.query(`
    CREATE TABLE IF NOT EXISTS public.institute_adaptive_configs (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      institute_id UUID,
      config_name TEXT NOT NULL,
      config_type TEXT DEFAULT 'adaptive_test',
      parameters_json JSONB DEFAULT '{}'::jsonb,
      is_active BOOLEAN DEFAULT true,
      created_by UUID,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    )
  `);
  console.log('  ✓ institute_adaptive_configs');

  console.log('[ADAPTIVE ENGINE SCHEMA] All 10 tables created successfully.');
  await db.end();
}

migrate().catch(err => {
  console.error('[ADAPTIVE ENGINE SCHEMA] Migration failed:', err.stack);
  process.exit(1);
});
